### ISSUE TITLE
Anzeige von Bildern auf GitHub und GitHub Pages

### ISSUE THREAD

**Issue by felixlohmeier** [remooda/bain#1]
Ich lese gerade
> Nun wird das Bild im GitHub-Branch nicht angezeigt, dafür auf der öffentlichen Blog-Seite.

Das liegt, denke ich, an den zwei geschweiften Klammern `{{`, die noch im Code stehen. Wenn diese entfernt werden, sollte es auch bei GitHub https://github.com/remooda/bain/blob/master/_posts/2020-09-17-tag1.md korrekt angezeigt werden.

**Comment by remooda** [comment]
Danke für den Tipp. Aber es hat auch noch 2 schliessende }} Klammern. Ich
habe verschiedene Dinge ausprobiert, aber es klappt trotzdem nicht.. (Das
heisst, einmal ohne Klammern, einmal nur mit einer, einmal ganz anders...
Aber auch nicht schlimm, wenns im Branch nicht angezeigt wird.

Ich habe noch eine andere Frage: Ich konnte das Frameworks FA zwar
anpassen, es gab aber einen Fehler beim Import und jetzt habe ich alle
felder noch (sind also nicht hidden). Ich hoffe mal, das ist nicht weiter
schlimm.

Am Fr., 2. Okt. 2020 um 00:02 Uhr schrieb Felix Lohmeier <
notifications@github.com>:

**Comment by felixlohmeier** [comment]
Entschuldigung, ich hatte mich nicht klar ausgedrückt. Ich meinte den ganzen Teil mit den geschweiften Klammern. Ich habe dazu einen Pull Request erstellt, den Sie übernehmen können. Mit dieser Syntax sollte es sowohl in der Vorschauansicht auf GitHub als auch bei GitHub Pages klappen.
